[package]
name = "timestep_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", default-features = false, features = ["bevy_core_pipeline", "bevy_winit", "std", "x11"] }
